server:
  port: 8080

spring:
  application:
    name: Client-Management-Rest-Microservice

microserviceName:
  kafkaProducer: Kafka-Producer-Microservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka